# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [19]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([[0,1,0,1]]).T 

In [20]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0 
syn0 = 2*np.random.random((3,3)) - 1 #(3x3)
syn1 = 2*np.random.random((3,1)) - 1 #(3x1)

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）
print('originalWeights:\nsyn0:\n',syn0,'\nsyn1:\n',syn1)



originalWeights:
syn0:
 [[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.30887855 -0.20646505]] 
syn1:
 [[ 0.07763347]
 [-0.16161097]
 [ 0.370439  ]]


神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [21]:
for iter in range(10000):
    # forward propagation
    l0 = X                        #(4x3)
    l1 = nonlin(np.dot(l0,syn0))  #(4x3)(3x3)=(4x3) f1(s)
    l2 = nonlin(np.dot(l1,syn1))  #(4x3)(3x1)=(4x1) f2(z)

    l2_delta = (y - l2)*nonlin(l2,True) #(4x1)
    syn1 += np.dot(l1.T,l2_delta) #(3x4)(4x1)=(3x1)
    l1_delta = np.dot(((y - l2) * nonlin(l2,True)),syn1.T)*nonlin(l1,True) #(4x3)
    syn0 += np.dot(l0.T,l1_delta) #(3x4)(4x3)=((3x3))
    
print('NewWeights:\nsyn0:\n',syn0,'\nsyn1:\n',syn1)

NewWeights:
syn0:
 [[-0.10668529  0.43221247 -0.96422008]
 [ 3.80435852 -5.42885675 -1.45409604]
 [-1.28209666  2.02022362 -0.1151782 ]] 
syn1:
 [[ 5.99729205]
 [-6.89549353]
 [-0.98203359]]


In [22]:
#驗證
l0 = X                        #(4x3)
l1 = nonlin(np.dot(l0,syn0))  #(4x3)(3x3)=(4x3) f1(s)
l2 = nonlin(np.dot(l1,syn1))  #(4x3)(3x1)=(4x1) f2(z)
print(l2)

[[0.00522918]
 [0.9942999 ]
 [0.00449206]
 [0.99393349]]
